config/routes.rb
Rails.application.routes.draw do

  get "/posts/about_me",  to: "posts#about_me"

  get "/home/instagram",  to: "home#instagram"
  get "/map",  to: "home#map"

  get "/home",       to: "home#index"

  get  "/posts",     to: "posts#index" , as: :posts

  post "/posts",     to: "posts#create", as: :postpage
  get  "/posts/new", to: "posts#new", as: :new_post

  put  "/posts/:id", to: "posts#update", as: :post

  get  "/posts/:id/edit", to: "posts#edit", as: :edit_post

  delete "/posts/:id",     to: "posts#destroy", as: :delete_post

  root "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
  has_many :users, through: :comments
  # validates :title, presence: true, numericality: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments
  has_many :posts, through: :comments
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception


  def require_login
    if session[:user_id]
      #find user
    else
      redirect_to root_path
    end

  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index


  end

  def instagram
  end

  def map
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # before_action :require_login, only: [:new, :create, :edit, :update]

  def index
    @posts = Post.all

  end

  def new
    @post = Post.new
  end

  def create
    # raise params.inspect
    # @post = Post.new(title: params[:title], content: params[:content])
    @post = Post.new(params.require(:post).permit(:title, :content))
    # @post = Post.new(params.require(:banana).permit(:title, :content))
    if @post.save
      redirect_to postpage_path
    else
      render :new
    end
  end




  def edit
    #find_post
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to postpage_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to postpage_path
    end
  end

  # def find_post
  #   @post = Post.find(params[:id])
  # end

  def about_me
  end

  private

  def post_params
    params.require(:banana).permit(:title, :content,  :bootsy_image_gallery_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html />



<div class="pagebody">
<h1> PIBLOGINTHESKY </h1>


<!--
<hr>
Params: <%= params.inspect %>
<hr> -->

<!-- <form action='/' method="POST">
  <p>First Name:
  <input type="text" name="first_name" /></p>

  <p>Last Name:
  <input type="text" name="last_name" /></p>

  <p>Password:
  <input type="password" name="password" /></p>

  <input type="submit">

</form action> -->



</div>

app/views/home/instagram.html.erb
<div class=pagebody> <iframe src="http://snapwidget.com/in/?u=cGlfaW50aGVza3l8aW58MjAwfDN8MjB8fHllc3wxMHxub25lfG9uU3RhcnR8eWVzfG5v&ve=061014" title="Instagram Widget" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:660px; height:4400px"></iframe>
</div>

app/views/home/map.html.erb
 <div id="map">

<script>
var map = L.map('map').setView([47.6032124,-122.3403549], 12);


L.tileLayer('http://{s}.tiles.mapbox.com/v3/stephmpi.bf7f5510/{z}/{x}/{y}.png', {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
} ).addTo(map);

L.Control.geocoder().addTo(map);
//
// var myIcon = L.icon({
//     iconUrl: 'marker-icon.png',
//     iconRetinaUrl: 'marker-icon@2x.png',
//     iconSize: [38, 95],
//     iconAnchor: [22, 94],
//     popupAnchor: [-3, -76],
//     shadowUrl: 'my-icon-shadow.png',
//     shadowRetinaUrl: 'my-icon-shadow@2x.png',
//     shadowSize: [68, 95],
//     shadowAnchor: [22, 94]
// });
//
// L.marker([50.505, 30.57], {icon: myIcon}).addTo(map);
//


</script>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html />
<html>

<head>
  <title>Piblog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" /> -->
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

  <!--
   <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js">
   </script>
 -->


</head>
<body>
    <div class=top></div>
    <div class=bottom></div>
    <div class=left></div>
    <div class=right></div>

    <div class="header">
      <div style="text-align: center;"><img src = "/chonga.jpg" ></div>
      <p></p>
      <div class="links">
        <ul class="nav">
          <li><a href= "/">Home</a></li>
          <li><a href= "/posts/about_me">About</a>
            <!-- <ul class="dropdown">
              <li><a href= "/posts/about_me">Bio</a></li>
              <li><a href= "/contact">Contact</a></li>
            </ul> -->
          </li>
          <li>
            <div class="dropdown">
            <a id="dLabel" data-target="#" data-toggle="dropdown">
                {STUFF}
                  <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li><a href= "/posts/">Posts</a></li>
              <li><a href= "/home/instagram">Photostream</a></li>
              <li><a href= "/map">Map</a></li>
            </ul>
          </div>
        </li>


        </ul>
      </div>
    </div>






<%= yield %>

<div class="media">
  <a href= "https://twitter.com/pi_inthecloud"  target="_blank"><img src = "/twitter.png"></a>
  <a href= "https://github.com/piinthecloud"  target="_blank"><img src = "/Github.png"></a>
  <a href= "https://www.linkedin.com/pub/stephanie-pi/25/6ab/b44"  target="_blank"><img src = "/linkedin.png"></a>
  <!-- <a href= "https://pibloginthesky.wordpress.com/"><img src = "/wordpress.png"  target="_blank"></a> -->
</div>

</body>


</html>

app/views/posts/about_me.html.erb
<div class="about">



<img src="/thischick.jpg" width="200">

<h1>Latinx. Chonga. Coder.</h1>

<p> Chonga feminista with a knack for stirring the pot. Causing a ruckus in the Pacific North West since 2013.</p>

<p>This blog is about sex, coding, and racism.
</p>

<!-- <div bottom><footer>
</footer></div>


  <h1> "ლ!◍ᴥ◍!ლ" </h1> -->

</div>

app/views/posts/edit.html.erb
<div class="pagebody">

<h1>Edit</h1>
<h4> <%= @post.title.upcase %></h4>

<form action="/posts/<%= @post.id %>" method="POST">
  <input type="hidden" name="_method" value="PUT"/>
  title <input type="text" name="banana[title]" value="<%= @post.title %>"/>
  content <input type="text" name="banana[content]" value="<%= @post.content %>"/>

  <input type="submit" />


</form>

</div>

app/views/posts/index.html.erb
<div class="postbody">

<h3>POSTS</h3>

<h3><%= link_to "New Post", new_post_path %></h3>

<% @posts.each do |post| %>
  <article>

    <h4><%= post.title.html_safe %></h4>
    <p><%= post.content.html_safe %></p>
    <p><%= link_to "Edit", "/posts/#{post.id}/edit" %>
    <%= button_to "Delete", "/posts/#{post.id}", method: :delete %>
  </p>
<!--
      <%= link_to "delete", @post, method: :delete %> -->



    <hr>
  </article>
<% end %>




</div>

app/views/posts/new.html.erb
<div class="pagebody">


  <h1> NEW POST </h1>


<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<textarea id="post_content" class='wysihtml5' placeholder="Enter text ...">
    <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>


</textarea>

<script type="text/javascript">
  $(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>



<!--  ############################################################  -->




<!-- <form action="/posts" method="POST">
  title <input type="text" name="banana[title]" value="<%= @post.title %>"/>
  content <input type="text" name="banana[content]" value="<%= @post.content %>"/>
  <input type="submit" />
</form> -->



<!--  ############################################################  -->




<!-- <%= form_tag postpage_path do %>

  <%= hidden_field_tag :user_id, 1 %>
  <%= label_tag "banana[title]", "Title" %>
  <%= text_field_tag "banana[title]" %>

  <%= label_tag "banana[content]", "Content" %>
  <%= text_field_tag "banana[content]" %>


  <%= submit_tag%>

<% end %> -->

</div>